# Generated by Django 4.2.7 on 2025-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygeneration',
            name='background_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
