# Generated by Django 4.2.7 on 2025-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0002_storygeneration_background_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storygeneration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Story Generation', 'verbose_name_plural': 'Story Generations'},
        ),
        migrations.AddField(
            model_name='storygeneration',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storygeneration',
            name='story_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storygeneration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storygeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
